modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "companionpouch"
version = "0.1.0"
displayName = "Companion Pouch"
authors = "QiyanaMark, MaxTheMooshroom"
description = '''Adds pouches that allow bringing more than one companion at a time into a vault'''

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="CompanionWorkStation.png" #optional
#credits="Thanks for this example mod goes to Java" #optional

[[dependencies.companionpouch]]
modId = "the_vault"
mandatory = true
versionRange = "${vault_hunters_version_range}"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.companionpouch]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.companionpouch]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"